name: dfx-mgr
base: core22
version: '2023.2+git20240426.903898e'
summary: Utility to configure Progammable Logic on Xilinx FPGAs
description: |
  Daemon and command-line tool
  DFX-MGR provides infrastructure to abstract configuration and hardware resource
  management for dynamic deployment of accelerator across different platforms.

grade: devel
confinement: devmode

architectures:
  - arm64

package-repositories:
  - type: apt
    suites: [jammy-limerick]
    components: [public]
    url: http://oem.archive.canonical.com/updates
    key-id: 236252602787D6BDC2336849F9FDA6BED73CDC22
  - type: apt
    ppa: tchavadar/junk

slots:
  firmwares-dir:
    interface: content
    content: firmwares
    source:
      write:
        - $SNAP_COMMON/firmware.d

plugs:
  system-files:
    write:
      - /sys/kernel/config

apps:
  dfx-mgr:
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib
    command: bin/dfx-mgr-client
    plugs:
      - network
      - network-bind
      - system-files
  dfx-mgrd:
    command: scripts/dfx-mgrd-snap-wrapper.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - system-files

parts:
  dfx-mgr:
    # See 'snapcraft plugins'
    source: .
    plugin: cmake
    stage-packages:
      - libsystemd0
      - libdfx1.0
    build-packages:
      - libsystemd-dev
      - libdfx-dev
      - libwebsockets-dev
      - libdrm-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWITH_STATIC_LIB=yes
      - -DCMAKE_TOOLCHAIN_FILE=cross-linux-gcc
      - -DCMAKE_INCLUDE_PATH="../include"
      - -DCMAKE_LIBRARY_PATH="../opendfx-graph/drivers/XF2DFilter/src/lib/sw/aarch64-linux"
    organize:
      usr/bin/dfx-mgrd-static: bin/dfx-mgrd
      usr/bin/dfx-mgr-client-static: bin/dfx-mgr-client
  configure:
    source: .
    plugin: dump
    organize:
      src/scripts/dfx-mgrd-snap-wrapper.sh: scripts/dfx-mgrd-snap-wrapper.sh
      src/scripts/dfx-mgr-management-script.sh: scripts/dfx-mgr-management-script.sh
    stage:
      - scripts/dfx-mgrd-snap-wrapper.sh
      - scripts/dfx-mgr-management-script.sh
