name: dfx-mgr # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2022.1+20220908+deb' # just for humans, typically '1.2+git' or '1.3.2'
summary: Utility to configure Progammable Logic on Xilinx FPGAs # 79 char long summary
description: |
  Daemon and command-line tool
  DFX-MGR provides infrastructure to abstract configuration and hardware resource
  management for dynamic deployment of accelerator across different platforms.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    suites: [jammy-limerick]
    components: [public]
    url: http://oem.archive.canonical.com/updates
    key-id: 236252602787D6BDC2336849F9FDA6BED73CDC22
  - type: apt
    ppa: tchavadar/junk

build-packages:
  - libdfx-dev
  - libwebsockets-dev
  - libdrm-dev

slots:
  firmwares-dir:
    interface: content
    content: firmwares
    source:
      write:
        - $SNAP_COMMON/firmware.d

plugs:
  system-files:
    write:
      - /sys/kernel/config

apps:
  dfx-mgr:
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib
    command: bin/dfx-mgr-client
    plugs:
      - network
      - network-bind
      - system-files
  dfx-mgrd:
    command: scripts/dfx-mgrd-snap-wrapper.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - system-files

parts:
  dfx-mgr:
    # See 'snapcraft plugins'
    source: .
    plugin: cmake
    stage-packages:
      - libdfx-dev
      - libwebsockets-dev
      - libdrm-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWITH_STATIC_LIB=no
      - -DCMAKE_TOOLCHAIN_FILE=cross-linux-gcc
      - -DCMAKE_INCLUDE_PATH="../include"
      - -DCMAKE_LIBRARY_PATH="../opendfx-graph/drivers/XF2DFilter/src/lib/sw/aarch64-linux"
    organize:
      usr/bin/dfx-mgrd-share: bin/dfx-mgrd
      usr/bin/dfx-mgr-client-share: bin/dfx-mgr-client
  configure:
    source: .
    plugin: dump
    organize:
      src/scripts/dfx-mgrd-snap-wrapper.sh: scripts/dfx-mgrd-snap-wrapper.sh
    stage:
      - scripts/dfx-mgrd-snap-wrapper.sh
